<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="chethan" failures="0" tests="2" name="testRunners.FailedTestRunner" time="49.504" errors="2" timestamp="2025-08-03T11:58:42 IST" skipped="0">
  <testcase classname="testRunners.FailedTestRunner" name="runScenario" time="20.470">
    <error message="Cannot invoke &quot;com.aventstack.extentreports.ExtentTest.pass(String)&quot; because &quot;hooks.Hooks.test&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentTest.pass(String)" because "hooks.Hooks.test" is null
at hooks.Hooks.tearDown(Hooks.java:83)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <testcase classname="testRunners.FailedTestRunner" name="runScenario" time="29.034">
    <error message="Cannot invoke &quot;com.aventstack.extentreports.ExtentTest.pass(String)&quot; because &quot;hooks.Hooks.test&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentTest.pass(String)" because "hooks.Hooks.test" is null
at hooks.Hooks.tearDown(Hooks.java:83)
]]>
    </error>
  </testcase> <!-- runScenario -->
</testsuite> <!-- testRunners.FailedTestRunner -->
